### ISSUE TITLE
Guzzle error while sending sms

### ISSUE THREAD

**Issue by iovzt** [zelenin/sms_ru#21]
Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.

guzzlehttp/guzzle/src/Client.php:380 line

Please fix it,
Best regards, Alexandr.

**Comment by zelenin** [comment]
fixed in version 3.0.0

**Comment by iovzt** [comment]
Thanks a lot!
